FROM ubuntu:latest

#
# Identify the maintainer of an image
LABEL maintainer="aleksandar.radisavljevic@harness.io"

#
# Expose port 80
EXPOSE 80

#
# Last is the actual command to start up NGINX within our Container
CMD ["nginx", "-g", "daemon off;"]
